domain: hub.proffit.net
url: https://hub.proffit.net
#baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder
title: The Myrinathian Frontier docs
description: A D&D 5e Campaign played on Maury Island
markdown: kramdown
google_analytics: G-DF49WTWXBJ

# architect, cayman, dinky, hacker, leap-day, merlot, midnight, minimal, modernist
theme: architect
plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings

collections:
  - npcs
  - pcs
  - locations
  - species
  - players
  - mirrors