domain: hub.proffit.net
url: https://hub.proffit.net
#baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder
title: The Myrinathian Frontier
description: A D&D 5e Campaign played on Maury Island
markdown: kramdown
google_analytics: G-DF49WTWXBJ

theme: midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings
